<a href="https://colab.research.google.com/github/amdridce/Herramientas_analisis_de_datos/blob/main/Clases_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
numero = 5
print(numero)
print(type(numero))
texto = "Bienvenidos a clase"
print(texto)
print(type(texto))
boolean = True or False
print(type(boolean))

5
<class 'int'>
Bienvenidos a clase
<class 'str'>
<class 'bool'>


In [4]:
# Condicional if

x = 1
y = 847
if x > y :
  print("x es mayor o igual que y")
elif x == y :
    print("x es igual que y")
elif x < y :
  print("x es menor que y")

x es menor que y


In [5]:
# List/Array
print("##### lista_vacia #####")
lista_vacia = []
print(lista_vacia)

print("##### lista_texto #####")
lista_texto = ["leopardo","camello", "cocodrilo", "león"]
print(lista_texto)
print(lista_texto[0])

print("##### lista_numero #####")
lista_numero = [4, 6, 3, 8]
print(lista_numero)
print(lista_numero[1])

print("##### lista_boolean #####")
lista_boolean = [True, False, True, True]
print(lista_boolean)
print(lista_boolean[2])

print("##### largo de una lista #####")
print(len(lista_texto))
print(len(lista_numero))
print(len(lista_boolean))

# Agregando datos a una lista
print("##### lista_vacia #####")
lista_vacia.append("me gusta python")
lista_vacia.append("lento pero seguro")
print(lista_vacia)
print(len(lista_vacia))
lista_vacia.sort()
print(lista_vacia)

##### lista_vacia #####
[]
##### lista_texto #####
['leopardo', 'camello', 'cocodrilo', 'león']
leopardo
##### lista_numero #####
[4, 6, 3, 8]
6
##### lista_boolean #####
[True, False, True, True]
True
##### largo de una lista #####
4
4
4
##### lista_vacia #####
['me gusta python', 'lento pero seguro']
2
['lento pero seguro', 'me gusta python']


In [6]:
import time
print("Antes del time") 
time.sleep(3.5) 
print("Despues de 3.5 segundos.")


Antes del time
Despues de 3.5 segundos.


In [7]:
import datetime

tiempo_ahora = datetime.datetime.now()
print(tiempo_ahora)

2022-06-13 21:10:21.756619


In [8]:
# Importamos toda la librería datetime

ahora = datetime.datetime.now()
print("hora ejecución antes del time.sleep: {}".format(ahora))
time.sleep(5)
ahora = datetime.datetime.now()
print("hora ejecución después del time.sleep: {}".format(ahora))

hora ejecución antes del time.sleep: 2022-06-13 21:10:21.810643
hora ejecución después del time.sleep: 2022-06-13 21:10:26.817252


In [9]:
# Importamos solo la función datetime de la librería datetime

from datetime import datetime as dt

ahora = dt.now()
print("hora ejecución antes del time.sleep: {}".format(ahora))
time.sleep(5)
ahora = dt.now()
print("hora ejecución después del time.sleep: {}".format(ahora))

hora ejecución antes del time.sleep: 2022-06-13 21:10:26.886342
hora ejecución después del time.sleep: 2022-06-13 21:10:31.888166


In [10]:
# Iteraciones con for loop 

ahora = dt.now()
print("######### Hora ejecución antes del for: {}".format(ahora.strftime("%H:%M:%S")))
for elemento in lista_texto:
    print(elemento)
    print("Espera . . .")
    time.sleep(1)

final = dt.now()
print("########## Hora ejecución después del for: {}".format(ahora.strftime("%H:%M:%S")))
print("########## Tiempo de ejecución: {}".format(final - ahora))

######### Hora ejecución antes del for: 21:10:31
leopardo
Espera . . .
camello
Espera . . .
cocodrilo
Espera . . .
león
Espera . . .
########## Hora ejecución después del for: 21:10:31
########## Tiempo de ejecución: 0:00:04.035967


In [11]:
ahora = dt.now()
print("######### Hora ejecución antes del for: {}".format(ahora.strftime("%H:%M:%S")))
for numero in lista_numero:
    print(numero)
    print("Espera . . .")
    time.sleep(1)

final = dt.now()
print("########## Hora ejecución después del for: {}".format(ahora.strftime("%H:%M:%S")))
print("########## Tiempo de ejecución: {}".format(final - ahora))

######### Hora ejecución antes del for: 21:10:36
4
Espera . . .
6
Espera . . .
3
Espera . . .
8
Espera . . .
########## Hora ejecución después del for: 21:10:36
########## Tiempo de ejecución: 0:00:04.044191


In [37]:
# Revisando datos de una lista
print("########## lista_vacia ##########")
lista_vacia.clear() # Elimina todos los elementos de una lista
lista_vacia.append("cocodrilo")
lista_vacia.append("elefante")
lista_vacia.append("las plantas están muy verdes")
lista_vacia.append("león")
lista_vacia.append("me encanta el chocolate")
lista_vacia.append("puma")
lista_vacia.append("hace mucho frío")
lista_vacia.append("tengo ganas de comer helado")
print(lista_vacia)
print(lista_vacia[2])
print(lista_vacia[6])
print(lista_vacia[len(lista_vacia) - 1])

print(range(len(lista_vacia)))

print("===== Inicio de for =====")
for i in range(len(lista_vacia)):
    print('El elemento: "{}" está en la posición: {} '.format(lista_vacia[i], i))


########## lista_vacia ##########
['cocodrilo', 'elefante', 'las plantas están muy verdes', 'león', 'me encanta el chocolate', 'puma', 'hace mucho frío', 'tengo ganas de comer helado']
las plantas están muy verdes
hace mucho frío
tengo ganas de comer helado
range(0, 8)
===== Inicio de for =====
El elemento: "cocodrilo" está en la posición: 0 
El elemento: "elefante" está en la posición: 1 
El elemento: "las plantas están muy verdes" está en la posición: 2 
El elemento: "león" está en la posición: 3 
El elemento: "me encanta el chocolate" está en la posición: 4 
El elemento: "puma" está en la posición: 5 
El elemento: "hace mucho frío" está en la posición: 6 
El elemento: "tengo ganas de comer helado" está en la posición: 7 


In [38]:
print(lista_vacia[7])
lista_vacia[7] = "no tengo ganas de comer helado"
print(lista_vacia[7])

tengo ganas de comer helado
no tengo ganas de comer helado


In [39]:
# Usando replace

for i in range(len(lista_vacia)):
    print('Antes del replace el elemento: "{}" está en la posición: {} '.format(lista_vacia[i], i))
    if lista_vacia[i].find('no') != -1:
        lista_vacia[i] = lista_vacia[i].replace('no', 'si')
    print('Después del replace el elemento: "{}" está en la posición: {} '.format(lista_vacia[i], i))

Antes del replace el elemento: "cocodrilo" está en la posición: 0 
Después del replace el elemento: "cocodrilo" está en la posición: 0 
Antes del replace el elemento: "elefante" está en la posición: 1 
Después del replace el elemento: "elefante" está en la posición: 1 
Antes del replace el elemento: "las plantas están muy verdes" está en la posición: 2 
Después del replace el elemento: "las plantas están muy verdes" está en la posición: 2 
Antes del replace el elemento: "león" está en la posición: 3 
Después del replace el elemento: "león" está en la posición: 3 
Antes del replace el elemento: "me encanta el chocolate" está en la posición: 4 
Después del replace el elemento: "me encanta el chocolate" está en la posición: 4 
Antes del replace el elemento: "puma" está en la posición: 5 
Después del replace el elemento: "puma" está en la posición: 5 
Antes del replace el elemento: "hace mucho frío" está en la posición: 6 
Después del replace el elemento: "hace mucho frío" está en la posic

# NumPy

In [44]:
import numpy as np
import time

# Arreglo normal o de texto

arreglo_normal = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(arreglo_normal)
print(type(arreglo_normal))

arreglo_numpy = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arreglo_numpy)
print(type(arreglo_numpy))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'list'>
[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [45]:
########### arreglo de una dimensión ##############

print('########### arreglo de una dimensión ##############')
arr_una_dim = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr_una_dim)
print(arr_una_dim[0])

########### arreglo de dos dimensiones ##############

print("########### arreglo de dos dimensiones ##############")
arr_dos_dim = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
print(arr_dos_dim)
print(arr_dos_dim[1][0])
print(arr_dos_dim[0,0])

########### arreglo de tres dimensiones ##############

print('########### arreglo de tres dimensiones ##############')
arr_tres_dim = np.array([[[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]],
[[21,22,23,24,25,26,27,28,29,30],[31,32,33,34,35,36,37,38,39,40]]])
print(arr_tres_dim)
print(arr_tres_dim[1,0,0])
print(arr_tres_dim[1][0][0])

########### arreglo de una dimensión ##############
[ 1  2  3  4  5  6  7  8  9 10]
1
########### arreglo de dos dimensiones ##############
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
11
1
########### arreglo de tres dimensiones ##############
[[[ 1  2  3  4  5  6  7  8  9 10]
  [11 12 13 14 15 16 17 18 19 20]]

 [[21 22 23 24 25 26 27 28 29 30]
  [31 32 33 34 35 36 37 38 39 40]]]
21
21


In [46]:
########################## índice negativo ##########################

# viendo el ultimo elemento del arr_una_dim
print('########## indice negativo en una dimensión ##########')
print(arr_una_dim[-1])


# viendo el primer elemento de la ultima fila del arr_dos_dim
print('########## indice negativo en dos dimensiones ##########')
print(arr_dos_dim[-1,0])
print(arr_dos_dim[-1,-1])


# viendo el primer elemento del segundo vertice en la ultima fila del arr_tres_dim
print('########## indice negativo en tres dimensiones ##########')
print(arr_tres_dim[-1,1,0])
print(arr_tres_dim[-1,0,-5])

########## indice negativo en una dimensión ##########
10
########## indice negativo en dos dimensiones ##########
11
20
########## indice negativo en tres dimensiones ##########
31
26


In [47]:
########################## rangos ##########################

# recorriendo del 1 al 5 del arr_una_dim
print('########## rangos en una dimensión ##########')
print(arr_una_dim[0:5])
print(arr_una_dim[4:10])

########################## rangos con pasos ##########################
print('########## rangos con pasos en una dimensión ##########')
print(arr_una_dim[0:10:2])
print(arr_una_dim[0:10:3])

########## rangos en una dimensión ##########
[1 2 3 4 5]
[ 5  6  7  8  9 10]
########## rangos con pasos en una dimensión ##########
[1 3 5 7 9]
[ 1  4  7 10]


In [48]:
########################## recorriendo con rangos sin inicio ##########################
print('########## recorriendo con rangos sin inicio en una dimensión ##########')
print(arr_una_dim[:5])

########################## recorriendo con rangos sin fin ##########################
print('########## recorriendo con rangos sin fin en una dimensión ##########')
print(arr_una_dim[5:])

########################## recorriendo con rangos sin inicio y sin fin ##########################
print('########## recorriendo con rangos sin inicio y sin fin en una dimensión ##########')
print(arr_una_dim[:])


########################## recorriendo con rangos negativos ##########################
print('########## recorriendo con rangos negativos en una dimensión ##########')
print(arr_una_dim[-5:-1])
print(arr_una_dim[-5:])
print(arr_una_dim[-1:])

########## recorriendo con rangos sin inicio en una dimensión ##########
[1 2 3 4 5]
########## recorriendo con rangos sin fin en una dimensión ##########
[ 6  7  8  9 10]
########## recorriendo con rangos sin inicio y sin fin en una dimensión ##########
[ 1  2  3  4  5  6  7  8  9 10]
########## recorriendo con rangos negativos en una dimensión ##########
[6 7 8 9]
[ 6  7  8  9 10]
[10]


In [49]:
# Shape en una dimensión
print(arr_una_dim.shape)

# Shape en dos dimensiones
print(arr_dos_dim.shape)

# Shape en tres dimensiones
print(arr_tres_dim.shape)

(10,)
(2, 10)
(2, 2, 10)


In [51]:
# reshape en una dimensión
print('reshape de 5,2')
resha_arr_una_dim = arr_una_dim.reshape(5,2)
print(resha_arr_una_dim)

print('reshape de 2,5')
resha_arr_una_dim = arr_una_dim.reshape(2,5)
print(resha_arr_una_dim)

# reshape en dos dimensiones
print('reshape de 2,5,2')
resha_arr_dos_dim = arr_dos_dim.reshape(2,5,2)
print(resha_arr_dos_dim)

# reshape en tres dimensiones
print('reshape de 2,5,2,2')
resha_arr_tres_dim = arr_tres_dim.reshape(2,5,2,2)
print(resha_arr_tres_dim)

reshape de 5,2
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
reshape de 2,5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
reshape de 2,5,2
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]
reshape de 2,5,2,2
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]

  [[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]

  [[17 18]
   [19 20]]]


 [[[21 22]
   [23 24]]

  [[25 26]
   [27 28]]

  [[29 30]
   [31 32]]

  [[33 34]
   [35 36]]

  [[37 38]
   [39 40]]]]


In [52]:
# reshape con el comodin -1
print('reshape con el comodin -1,2')
print(arr_una_dim.shape)
resha_arr_una_dim_comodin = arr_una_dim.reshape(-1,2)
print(resha_arr_una_dim_comodin.shape)

# Volviendo a una dimensión
print('volviendo a una dimensión')
print(resha_arr_tres_dim.shape)
print(resha_arr_tres_dim.reshape(-1).shape)

reshape con el comodin -1,2
(10,)
(5, 2)
volviendo a una dimensión
(2, 5, 2, 2)
(40,)


In [53]:
# iterando una dimension con un for
print('iterando una dimension con un for')
for dato in arr_una_dim:
    print('viendo el dato: {} {}'.format(dato,type(dato)))
    time.sleep(1)

iterando una dimension con un for
viendo el dato: 1 <class 'numpy.int32'>
viendo el dato: 2 <class 'numpy.int32'>
viendo el dato: 3 <class 'numpy.int32'>
viendo el dato: 4 <class 'numpy.int32'>
viendo el dato: 5 <class 'numpy.int32'>
viendo el dato: 6 <class 'numpy.int32'>
viendo el dato: 7 <class 'numpy.int32'>
viendo el dato: 8 <class 'numpy.int32'>
viendo el dato: 9 <class 'numpy.int32'>
viendo el dato: 10 <class 'numpy.int32'>


In [54]:
# iterando dos dimensiones con un for
print('iterando dos dimensiones con un for')
print(arr_dos_dim.shape)
print(arr_dos_dim)
for fila in arr_dos_dim:
    print('viendo la fila: {} {}'.format(fila,type(fila)))
    for columna in fila:
        print('viendo la columna: {} {}'.format(columna,type(columna)))
        # time.sleep(1)

iterando dos dimensiones con un for
(2, 10)
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
viendo la fila: [ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>
viendo la columna: 1 <class 'numpy.int32'>
viendo la columna: 2 <class 'numpy.int32'>
viendo la columna: 3 <class 'numpy.int32'>
viendo la columna: 4 <class 'numpy.int32'>
viendo la columna: 5 <class 'numpy.int32'>
viendo la columna: 6 <class 'numpy.int32'>
viendo la columna: 7 <class 'numpy.int32'>
viendo la columna: 8 <class 'numpy.int32'>
viendo la columna: 9 <class 'numpy.int32'>
viendo la columna: 10 <class 'numpy.int32'>
viendo la fila: [11 12 13 14 15 16 17 18 19 20] <class 'numpy.ndarray'>
viendo la columna: 11 <class 'numpy.int32'>
viendo la columna: 12 <class 'numpy.int32'>
viendo la columna: 13 <class 'numpy.int32'>
viendo la columna: 14 <class 'numpy.int32'>
viendo la columna: 15 <class 'numpy.int32'>
viendo la columna: 16 <class 'numpy.int32'>
viendo la columna: 17 <class 'numpy.int32'>
viendo

In [55]:
# iterando tres dimensiones con un for
print('iterando tres dimensiones con un for')
print(arr_tres_dim.shape)
print(arr_tres_dim)
for fila in arr_tres_dim:
    print('viendo la fila: {} {}'.format(fila,type(fila)))
    for columna in fila:
        print('viendo la columna: {} {}'.format(columna,type(columna)))
        for vertice in columna:
            print('viendo el vertice: {} {}'.format(vertice,type(vertice)))
            time.sleep(0.2)

iterando tres dimensiones con un for
(2, 2, 10)
[[[ 1  2  3  4  5  6  7  8  9 10]
  [11 12 13 14 15 16 17 18 19 20]]

 [[21 22 23 24 25 26 27 28 29 30]
  [31 32 33 34 35 36 37 38 39 40]]]
viendo la fila: [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]] <class 'numpy.ndarray'>
viendo la columna: [ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>
viendo el vertice: 1 <class 'numpy.int32'>
viendo el vertice: 2 <class 'numpy.int32'>
viendo el vertice: 3 <class 'numpy.int32'>
viendo el vertice: 4 <class 'numpy.int32'>
viendo el vertice: 5 <class 'numpy.int32'>
viendo el vertice: 6 <class 'numpy.int32'>
viendo el vertice: 7 <class 'numpy.int32'>
viendo el vertice: 8 <class 'numpy.int32'>
viendo el vertice: 9 <class 'numpy.int32'>
viendo el vertice: 10 <class 'numpy.int32'>
viendo la columna: [11 12 13 14 15 16 17 18 19 20] <class 'numpy.ndarray'>
viendo el vertice: 11 <class 'numpy.int32'>
viendo el vertice: 12 <class 'numpy.int32'>
viendo el vertice: 13 <class 'numpy.

In [56]:
# iterando una dimension con for cambiando el shape
print('iterando una dimension con for cambiando el shape')
print(arr_tres_dim.shape)
print(arr_tres_dim)
for dato in arr_tres_dim.reshape(-1):
    print('viendo el dato: {} {}'.format(dato,type(dato)))
    time.sleep(0.5)

iterando una dimension con for cambiando el shape
(2, 2, 10)
[[[ 1  2  3  4  5  6  7  8  9 10]
  [11 12 13 14 15 16 17 18 19 20]]

 [[21 22 23 24 25 26 27 28 29 30]
  [31 32 33 34 35 36 37 38 39 40]]]
viendo el dato: 1 <class 'numpy.int32'>
viendo el dato: 2 <class 'numpy.int32'>
viendo el dato: 3 <class 'numpy.int32'>
viendo el dato: 4 <class 'numpy.int32'>
viendo el dato: 5 <class 'numpy.int32'>
viendo el dato: 6 <class 'numpy.int32'>
viendo el dato: 7 <class 'numpy.int32'>
viendo el dato: 8 <class 'numpy.int32'>
viendo el dato: 9 <class 'numpy.int32'>
viendo el dato: 10 <class 'numpy.int32'>
viendo el dato: 11 <class 'numpy.int32'>
viendo el dato: 12 <class 'numpy.int32'>
viendo el dato: 13 <class 'numpy.int32'>
viendo el dato: 14 <class 'numpy.int32'>
viendo el dato: 15 <class 'numpy.int32'>
viendo el dato: 16 <class 'numpy.int32'>
viendo el dato: 17 <class 'numpy.int32'>
viendo el dato: 18 <class 'numpy.int32'>
viendo el dato: 19 <class 'numpy.int32'>
viendo el dato: 20 <class 'nu

In [57]:
# iterando con nditer
print('iterando con nditer')
print(arr_tres_dim.shape)
print(arr_tres_dim)
for dato in np.nditer(arr_tres_dim):
    print('viendo el dato: {} {}'.format(dato,type(dato)))
    time.sleep(0.5)

iterando con nditer
(2, 2, 10)
[[[ 1  2  3  4  5  6  7  8  9 10]
  [11 12 13 14 15 16 17 18 19 20]]

 [[21 22 23 24 25 26 27 28 29 30]
  [31 32 33 34 35 36 37 38 39 40]]]
viendo el dato: 1 <class 'numpy.ndarray'>
viendo el dato: 2 <class 'numpy.ndarray'>
viendo el dato: 3 <class 'numpy.ndarray'>
viendo el dato: 4 <class 'numpy.ndarray'>
viendo el dato: 5 <class 'numpy.ndarray'>
viendo el dato: 6 <class 'numpy.ndarray'>
viendo el dato: 7 <class 'numpy.ndarray'>
viendo el dato: 8 <class 'numpy.ndarray'>
viendo el dato: 9 <class 'numpy.ndarray'>
viendo el dato: 10 <class 'numpy.ndarray'>
viendo el dato: 11 <class 'numpy.ndarray'>
viendo el dato: 12 <class 'numpy.ndarray'>
viendo el dato: 13 <class 'numpy.ndarray'>
viendo el dato: 14 <class 'numpy.ndarray'>
viendo el dato: 15 <class 'numpy.ndarray'>
viendo el dato: 16 <class 'numpy.ndarray'>
viendo el dato: 17 <class 'numpy.ndarray'>
viendo el dato: 18 <class 'numpy.ndarray'>
viendo el dato: 19 <class 'numpy.ndarray'>
viendo el dato: 20 <c

In [58]:
# iterando dos dimensiones con ednumerate
print('iterando dos dimensiones con ednumerate')
print(arr_dos_dim.shape)
print(arr_dos_dim)
for indice,dato in np.ndenumerate(arr_dos_dim):
    print('∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞')
    print('viendo el indice: {} {}'.format(indice,type(indice)))
    print('viendo el dato: {} {}'.format(dato,type(dato)))
    time.sleep(0.5)

iterando dos dimensiones con ednumerate
(2, 10)
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 0) <class 'tuple'>
viendo el dato: 1 <class 'numpy.int32'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 1) <class 'tuple'>
viendo el dato: 2 <class 'numpy.int32'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 2) <class 'tuple'>
viendo el dato: 3 <class 'numpy.int32'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 3) <class 'tuple'>
viendo el dato: 4 <class 'numpy.int32'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 4) <class 'tuple'>
viendo el dato: 5 <class 'numpy.int32'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 5) <class 'tuple'>
viendo el dato: 6 <class 'numpy.int32'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 6) <cl

In [59]:
# iterando tres dimensiones con ednumerate
print('iterando tres dimensiones con ednumerate')
print(arr_tres_dim.shape)
print(arr_tres_dim)
for indice,dato in np.ndenumerate(arr_tres_dim):
    print('∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞')
    print('viendo el indice: {} {}'.format(indice,type(indice)))
    print('viendo el dato: {} {}'.format(dato,type(dato)))
    time.sleep(0.5)

iterando tres dimensiones con ednumerate
(2, 2, 10)
[[[ 1  2  3  4  5  6  7  8  9 10]
  [11 12 13 14 15 16 17 18 19 20]]

 [[21 22 23 24 25 26 27 28 29 30]
  [31 32 33 34 35 36 37 38 39 40]]]
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 0, 0) <class 'tuple'>
viendo el dato: 1 <class 'numpy.int32'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 0, 1) <class 'tuple'>
viendo el dato: 2 <class 'numpy.int32'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 0, 2) <class 'tuple'>
viendo el dato: 3 <class 'numpy.int32'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 0, 3) <class 'tuple'>
viendo el dato: 4 <class 'numpy.int32'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 0, 4) <class 'tuple'>
viendo el dato: 5 <class 'numpy.int32'>
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
viendo el indice: (0, 0, 5) <class 'tuple'>
viendo el dato: 6 <class '

In [60]:
# concatenando nparreglos
arreglo_uno = np.array([91,82,33,74,92])
arreglo_dos = np.array([12,13,45,34,63])

arreglo_concatenado = np.concatenate((arreglo_uno,arreglo_dos))
print(arreglo_concatenado)

[91 82 33 74 92 12 13 45 34 63]


In [61]:
# concatenando nparreglos con axis = 0
arreglo_concatenado = np.concatenate((arreglo_uno,arreglo_dos),axis=0)
print(arreglo_concatenado)

[91 82 33 74 92 12 13 45 34 63]


In [62]:
# concatenando nparreglos con axis = 0
arreglo_dos_dim_uno = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('shape de arreglo_dos_dim_uno: {}'.format(arreglo_dos_dim_uno.shape))
arreglo_dos_dim_dos = np.array([[11,12,13,14,15],[16,17,18,19,20]])
print('shape de arreglo_dos_dim_dos: {}'.format(arreglo_dos_dim_dos.shape))

arreglo_concat_axis0 = np.concatenate((arreglo_dos_dim_uno,arreglo_dos_dim_dos),axis=0)
print(arreglo_concat_axis0)
print(arreglo_concat_axis0.shape)

print('∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞')
# concatenando nparreglos con axis = 1
arreglo_concat_axis1 = np.concatenate((arreglo_dos_dim_uno,arreglo_dos_dim_dos),axis=1)
#print(arreglo_concat_axis1)
print(arreglo_concat_axis1.shape)


# haciendo reshape para pasar a 5 dimensiones
arr_cinco_dim_uno = arreglo_dos_dim_uno.reshape(1,1,5,2,1)
print(arr_cinco_dim_uno)
print(arr_cinco_dim_uno.shape)
arr_cinco_dim_dos = arreglo_dos_dim_dos.reshape(1,1,5,2,1)
print(arr_cinco_dim_dos.shape)

# concatenando nparreglos con axis = 4
arreglo_concat_axis4 = np.concatenate((arr_cinco_dim_uno,arr_cinco_dim_dos),axis=4)
print(arreglo_concat_axis4)
print(arreglo_concat_axis4.shape)

shape de arreglo_dos_dim_uno: (2, 5)
shape de arreglo_dos_dim_dos: (2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(4, 5)
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
(2, 10)
[[[[[ 1]
    [ 2]]

   [[ 3]
    [ 4]]

   [[ 5]
    [ 6]]

   [[ 7]
    [ 8]]

   [[ 9]
    [10]]]]]
(1, 1, 5, 2, 1)
(1, 1, 5, 2, 1)
[[[[[ 1 11]
    [ 2 12]]

   [[ 3 13]
    [ 4 14]]

   [[ 5 15]
    [ 6 16]]

   [[ 7 17]
    [ 8 18]]

   [[ 9 19]
    [10 20]]]]]
(1, 1, 5, 2, 2)


In [63]:
# uniendo nparreglos con np.stack
print('shape de arreglo_dos_dim_uno: {}'.format(arreglo_dos_dim_uno.shape))
print('shape de arreglo_dos_dim_dos: {}'.format(arreglo_dos_dim_dos.shape))
print('el shape de union con concatenate axis = 0: {}'.format(arreglo_concat_axis0.shape))

# uniendo nparreglos con np.stack axis = 0
arreglo_stack_axis0 = np.stack((arreglo_dos_dim_uno,arreglo_dos_dim_dos),axis=0)
print(arreglo_stack_axis0)
print(arreglo_stack_axis0.shape)

# uniendo nparreglos con np.stack axis = 1
arreglo_stack_axis1 = np.stack((arreglo_dos_dim_uno,arreglo_dos_dim_dos),axis=1)
print(arreglo_stack_axis1)
print(arreglo_stack_axis1.shape)

# uniendo nparreglos con np.stack axis = 2
arreglo_stack_axis2 = np.stack((arreglo_dos_dim_uno,arreglo_dos_dim_dos),axis=2)
print(arreglo_stack_axis2)
print(arreglo_stack_axis2.shape)

shape de arreglo_dos_dim_uno: (2, 5)
shape de arreglo_dos_dim_dos: (2, 5)
el shape de union con concatenate axis = 0: (4, 5)
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
(2, 2, 5)
[[[ 1  2  3  4  5]
  [11 12 13 14 15]]

 [[ 6  7  8  9 10]
  [16 17 18 19 20]]]
(2, 2, 5)
[[[ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]
  [ 5 15]]

 [[ 6 16]
  [ 7 17]
  [ 8 18]
  [ 9 19]
  [10 20]]]
(2, 5, 2)


In [64]:
# uniendo nparreglos con np.hstack
arreglo_hstack = np.hstack((arreglo_dos_dim_uno,arreglo_dos_dim_dos))
print(arreglo_hstack)
print(arreglo_hstack.shape)

# uniendo nparreglos con np.vstack
arreglo_vstack = np.vstack((arreglo_dos_dim_uno,arreglo_dos_dim_dos))
print(arreglo_vstack)
print(arreglo_vstack.shape)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]
(2, 10)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(4, 5)


In [65]:
# operaciones algebraicas de numeros enteros con los nparreglos
print('operaciones algebraicas de numeros enteros con los nparreglos')
print('arreglo base')
print(arreglo_vstack)

print('arreglo_vstack + 2')
print(arreglo_vstack+2)

print('arreglo_vstack - 2')
print(arreglo_vstack-2)

print('arreglo_vstack * 2')
print(arreglo_vstack*2)

operaciones algebraicas de numeros enteros con los nparreglos
arreglo base
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
arreglo_vstack + 2
[[ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]]
arreglo_vstack - 2
[[-1  0  1  2  3]
 [ 4  5  6  7  8]
 [ 9 10 11 12 13]
 [14 15 16 17 18]]
arreglo_vstack * 2
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]


In [66]:
# aprendiendo a usar el where
print('aprendiendo a usar el where')

arreglo = np.array([87,12,37,81,34,91,41,29,81,98])

resultado_busqueda = np.where(arreglo>=81)
print(resultado_busqueda)

print('corroborando el resultado de la busqueda')
print(arreglo[resultado_busqueda])

aprendiendo a usar el where
(array([0, 3, 5, 8, 9], dtype=int64),)
corroborando el resultado de la busqueda
[87 81 91 81 98]


In [67]:
# buscando todos los elementos que son multiplos de 3 en arreglo
print('buscando todos los elementos que son multiplos de 3 en arreglo')
arreglo_multiplos_tres = np.where(arreglo%3==0)
print(arreglo_multiplos_tres)

print('corroborando el resultado de la busqueda')
print(arreglo[arreglo_multiplos_tres])

buscando todos los elementos que son multiplos de 3 en arreglo
(array([0, 1, 3, 8], dtype=int64),)
corroborando el resultado de la busqueda
[87 12 81 81]


In [68]:
# ordenando los elementos de un arreglo
print('ordenando los elementos de un arreglo')
arreglo = np.array(['el','niño','se','cambio','de','casa','porque','no','le','gustaba','la','suya'])
print(arreglo)

arreglo_ordenado = np.sort(arreglo)
print(arreglo_ordenado)

ordenando los elementos de un arreglo
['el' 'niño' 'se' 'cambio' 'de' 'casa' 'porque' 'no' 'le' 'gustaba' 'la'
 'suya']
['cambio' 'casa' 'de' 'el' 'gustaba' 'la' 'le' 'niño' 'no' 'porque' 'se'
 'suya']


In [69]:
# realizando una busqueda con for
arreglo = np.array(['el','niño','se','cambio','de','casa','porque','no','le','gustaba','la','suya'])

filtro = []

for dato in arreglo:
    if dato.find('e') != -1:
        filtro.append(True)
    elif dato.find('o') != -1:
        filtro.append(True)
    else:
        filtro.append(False)

print(filtro)

resultado_filtro = arreglo[filtro]
print(resultado_filtro)

[True, True, True, True, True, False, True, True, True, False, False, False]
['el' 'niño' 'se' 'cambio' 'de' 'porque' 'no' 'le']


In [70]:
# realizando filtro simple
print('realizando filtro simple')

arreglo = np.array([87,12,37,81,34,91,41,29,81,98])

filtro = arreglo >= 81

print(filtro)

arreglo_filtrado = arreglo[filtro]
print(arreglo_filtrado)

realizando filtro simple
[ True False False  True False  True False False  True  True]
[87 81 91 81 98]


In [71]:
# operaciones algebraicas entre nparreglos
print('operaciones algebraicas entre nparreglos')

arr_uno = np.array([91,82,33,74,92])
arr_dos = np.array([1,2,3,4,5])

print('suma entre arr_uno y arr_dos')
print(np.add(arr_uno,arr_dos))

print('resta entre arr_uno y arr_dos')
print(np.subtract(arr_uno,arr_dos))

print('multiplicacion entre arr_uno y arr_dos')
print(np.multiply(arr_uno,arr_dos))

print('division entre arr_uno y arr_dos')
print(np.divide(arr_uno,arr_dos))

print('divmod entre arr_uno y arr_dos')
print(np.divmod(arr_uno,arr_dos)[0])
print(np.divmod(arr_uno,arr_dos)[1])

operaciones algebraicas entre nparreglos
suma entre arr_uno y arr_dos
[92 84 36 78 97]
resta entre arr_uno y arr_dos
[90 80 30 70 87]
multiplicacion entre arr_uno y arr_dos
[ 91 164  99 296 460]
division entre arr_uno y arr_dos
[91.  41.  11.  18.5 18.4]
divmod entre arr_uno y arr_dos
[91 41 11 18 18]
[0 0 0 2 2]
